// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk8qZVB-bkeOBWIGdVaXeIaxYIfmj1cjQ',
    appId: '1:749162325727:web:100b4daab6ba3c16da2b6a',
    messagingSenderId: '749162325727',
    projectId: 'magazine-info-d423b',
    authDomain: 'magazine-info-d423b.firebaseapp.com',
    storageBucket: 'magazine-info-d423b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuaTdo78t8DpyAOo7FRt2WQMMc7tv8QMo',
    appId: '1:749162325727:android:c810dd19d5b655a5da2b6a',
    messagingSenderId: '749162325727',
    projectId: 'magazine-info-d423b',
    storageBucket: 'magazine-info-d423b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxN-aaFxNLQS9hdaCMwoUQLdVsm8-Dtzs',
    appId: '1:749162325727:ios:21cac343279dc004da2b6a',
    messagingSenderId: '749162325727',
    projectId: 'magazine-info-d423b',
    storageBucket: 'magazine-info-d423b.firebasestorage.app',
    iosBundleId: 'com.example.appli',
  );
}
